export const INIT = 'INIT';

export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const UPDATE_HREF = 'UPDATE_HREF';
export const UPDATE_HISTORY_POSITION = 'UPDATE_HISTORY_POSITION';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';

export const FETCH = 'FETCH';
export const FETCH_COMMIT = 'FETCH_COMMIT';
export const FETCH_ROLLBACK = 'FETCH_ROLLBACK';

export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_MORE_COMMIT = 'FETCH_MORE_COMMIT';
export const FETCH_MORE_ROLLBACK = 'FETCH_MORE_ROLLBACK';

export const ADD_LINKS = 'ADD_LINKS';
export const ADD_LINKS_COMMIT = 'ADD_LINKS_COMMIT';
export const ADD_LINKS_ROLLBACK = 'ADD_LINKS_ROLLBACK';

export const UPDATE_LINKS = 'UPDATE_LINKS';

export const DELETE_LINKS = 'DELETE_LINKS';
export const DELETE_LINKS_COMMIT = 'DELETE_LINKS_COMMIT';
export const DELETE_LINKS_ROLLBACK = 'DELETE_LINKS_ROLLBACK';

export const MOVE_LINKS_ADD_STEP = 'MOVE_LINKS_ADD_STEP';
export const MOVE_LINKS_ADD_STEP_COMMIT = 'MOVE_LINKS_ADD_STEP_COMMIT';
export const MOVE_LINKS_ADD_STEP_ROLLBACK = 'MOVE_LINKS_ADD_STEP_ROLLBACK';
export const MOVE_LINKS_DELETE_STEP = 'MOVE_LINKS_DELETE_STEP';
export const MOVE_LINKS_DELETE_STEP_COMMIT = 'MOVE_LINKS_DELETE_STEP_COMMIT';
export const MOVE_LINKS_DELETE_STEP_ROLLBACK = 'MOVE_LINKS_DELETE_STEP_ROLLBACK';

export const CANCEL_DIED_LINKS = 'CANCEL_DIED_LINKS';

export const DELETE_OLD_LINKS_IN_TRASH = 'DELETE_OLD_LINKS_IN_TRASH';
export const DELETE_OLD_LINKS_IN_TRASH_COMMIT = 'DELETE_OLD_LINKS_IN_TRASH_COMMIT';
export const DELETE_OLD_LINKS_IN_TRASH_ROLLBACK = 'DELETE_OLD_LINKS_IN_TRASH_ROLLBACK';

export const EXTRACT_CONTENTS = 'EXTRACT_CONTENTS';
export const EXTRACT_CONTENTS_COMMIT = 'EXTRACT_CONTENTS_COMMIT';
export const EXTRACT_CONTENTS_ROLLBACK = 'EXTRACT_CONTENTS_ROLLBACK';

export const UPDATE_STATUS = 'UPDATE_STATUS';

export const UPDATE_CARD_ITEM_MENU_POPUP_POSITION = 'UPDATE_CARD_ITEM_MENU_POPUP_POSITION';

export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';

export const UPDATE_BULK_EDITING = 'UPDATE_BULK_EDITING';

export const ADD_SELECTED_LINK_IDS = 'ADD_SELECTED_LINK_IDS';
export const DELETE_SELECTED_LINK_IDS = 'DELETE_SELECTED_LINK_IDS';
export const CLEAR_SELECTED_LINK_IDS = 'CLEAR_SELECTED_LINK_IDS';

export const UPDATE_EXPORT_ALL_DATA_PROGRESS = 'UPDATE_EXPORT_ALL_DATA_PROGRESS';
export const UPDATE_DELETE_ALL_DATA_PROGRESS = 'UPDATE_DELETE_ALL_DATA_PROGRESS';

export const ADD_LIST_NAMES = 'ADD_LIST_NAMES';
export const ADD_LIST_NAMES_COMMIT = 'ADD_LIST_NAMES_COMMIT';
export const ADD_LIST_NAMES_ROLLBACK = 'ADD_LIST_NAMES_ROLLBACK';

export const UPDATE_LIST_NAMES = 'UPDATE_LIST_NAMES';
export const UPDATE_LIST_NAMES_COMMIT = 'UPDATE_LIST_NAMES_COMMIT';
export const UPDATE_LIST_NAMES_ROLLBACK = 'UPDATE_LIST_NAMES_ROLLBACK';

export const MOVE_LIST_NAME = 'MOVE_LIST_NAME';
export const MOVE_LIST_NAME_COMMIT = 'MOVE_LIST_NAME_COMMIT';
export const MOVE_LIST_NAME_ROLLBACK = 'MOVE_LIST_NAME_ROLLBACK';

export const DELETE_LIST_NAMES = 'DELETE_LIST_NAMES';
export const DELETE_LIST_NAMES_COMMIT = 'DELETE_LIST_NAMES_COMMIT';
export const DELETE_LIST_NAMES_ROLLBACK = 'DELETE_LIST_NAMES_ROLLBACK';

export const UPDATE_DELETING_LIST_NAME = 'UPDATE_DELETING_LIST_NAME';

export const RETRY_ADD_LIST_NAMES = 'RETRY_ADD_LIST_NAMES';
export const RETRY_UPDATE_LIST_NAMES = 'RETRY_UPDATE_LIST_NAMES';
export const RETRY_MOVE_LIST_NAME = 'RETRY_MOVE_LIST_NAME';
export const RETRY_DELETE_LIST_NAMES = 'RETRY_DELETE_LIST_NAMES';

export const CANCEL_DIED_LIST_NAMES = 'CANCEL_DIED_LIST_NAMES';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_COMMIT = 'UPDATE_SETTINGS_COMMIT';
export const UPDATE_SETTINGS_ROLLBACK = 'UPDATE_SETTINGS_ROLLBACK';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
