import React from 'react';
import { View, TouchableOpacity, Linking } from 'react-native';
import { connect } from 'react-redux';

import { getThemeMode } from '../selectors';

import { withTailwind } from '.';
import Text from './CustomText';

class SettingsPopupAccount extends React.PureComponent<any, any> {

  render() {
    const { tailwind } = this.props;

    return (
      <View style={tailwind('p-4 md:p-6')}>
        <View style={tailwind('border-b border-gray-200 blk:border-gray-700 md:hidden')}>
          <TouchableOpacity onPress={this.props.onSidebarOpenBtnClick} style={tailwind('pb-1')}>
            <Text style={tailwind('text-sm font-normal text-gray-500 blk:text-gray-400')}>{'<'} <Text style={tailwind('text-sm font-normal text-gray-500 blk:text-gray-400')}>Settings</Text></Text>
          </TouchableOpacity>
          <Text style={tailwind('pb-2 text-xl font-medium leading-5 text-gray-800 blk:text-gray-100')}>Account</Text>
        </View>
        <View style={tailwind('mt-6 md:mt-0')}>
          <Text style={tailwind('text-base font-medium leading-4 text-gray-800 blk:text-gray-100')}>Stacks Account</Text>
          <Text style={tailwind('mt-3.5 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>Your account is <Text onPress={() => Linking.openURL('https://docs.stacks.co/concepts/network-fundamentals/accounts')} style={tailwind('text-base font-normal leading-6.5 text-gray-500 underline blk:text-gray-400')}>a Stacks account</Text>, and a Stacks account is used to access <Text onPress={() => Linking.openURL('https://explorer.hiro.so')} style={tailwind('text-base font-normal leading-6.5 text-gray-500 underline blk:text-gray-400')}>the Stacks blockchain</Text> and <Text onPress={() => Linking.openURL('https://docs.stacks.co/concepts/gaia')} style={tailwind('text-base font-normal leading-6.5 text-gray-500 underline blk:text-gray-400')}>a Stacks data server</Text>. The Stacks blockchain stores your account information, such as your username, profile, and data server location. A Stacks data server stores your encrypted app data, such as all your saved links.</Text>
          <Text style={tailwind('mt-4 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>Your Secret Key acts like a password. It&apos;s only known to you, ensuring that only you can decrypt your data and see the content inside. If you lose it, there is no way to retrieve it back. You need to keep it safe.</Text>
          <Text style={tailwind('mt-4 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>Your Secret Key cannot be changed or reset. As it&apos;s used to encrypt your content file by file, if you change your Secret Key, every file needs to be decrypted with your old Secret Key and encrypted again with your new Secret Key.</Text>
        </View>
        <View style={tailwind('mt-8 mb-4')}>
          <Text style={tailwind('text-base font-medium leading-4 text-red-600 blk:text-red-500')}>Delete Account</Text>
          <Text style={tailwind('mt-3.5 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>No one without your Secret Key can access your account or content, so you don&apos;t need to delete them. To delete all your data, please go to Settings &rarr; Data &rarr; Delete All Data.</Text>
          <Text style={tailwind('mt-4 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>Your Stacks account is generated by a cryptographic algorithm and your Secret Key. Forgetting your Secret Key is the only way to delete your account.</Text>
          <Text style={tailwind('mt-4 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>If you&apos;ve started with us, we create your Stacks account without a username, profile, or data server location. So, no data is stored in the Stacks blockchain, and your data is stored in our provided server by default.</Text>
          <Text style={tailwind('mt-4 text-base font-normal leading-6.5 text-gray-500 blk:text-gray-400')}>After you delete all your data in Settings &rarr; Data &rarr; Delete All Data, there&apos;s nothing left. You can forget your Secret Key. It&apos;s permanently deleting your account.</Text>
        </View>
      </View>
    );
  }
}

const mapStateToProps = (state, props) => {
  return {
    themeMode: getThemeMode(state),
  };
};

export default connect(mapStateToProps)(withTailwind(SettingsPopupAccount));
