'use client';
import React from 'react';
import { connect } from 'react-redux';

import { getSafeAreaWidth, getThemeMode } from '../selectors';
import { SHOW_BLANK } from '../types/const';

import { withTailwind } from '.';
import TopBar from './TopBar';
import Footer from './Footer';
import Link from './CustomLink';

class Terms extends React.PureComponent<any, any> {

  componentDidMount() {
    window.scrollTo(0, 0);
  }

  render() {
    const { tailwind } = this.props;

    return (
      <React.Fragment>
        <TopBar rightPane={SHOW_BLANK} />
        <div className={tailwind('mx-auto w-full max-w-6xl bg-white')}>
          <div className={tailwind('mx-auto w-full max-w-3xl bg-white px-4 pt-16 pb-4 text-gray-500 md:px-6 lg:px-8')}>
            <h1 className={tailwind('text-center text-3xl font-extrabold text-gray-900 sm:text-4xl')}>Terms of Service</h1>
            <p className={tailwind('pt-8 leading-7')}>Last updated: 17 Apr 2024</p>
            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Intro</h2>
            <p className={tailwind('pt-3 leading-7')}>By accessing, browsing and/or using our website(s) (each, a &quot;Site&quot; and collectively, the &quot;Site(s)&quot;), downloading, installing and/or using any mobile device software application owned, controlled or offered by <a className={tailwind('rounded-xs font-medium text-gray-900 underline focus:outline-none focus:ring')} href="https://www.stxapps.com" target="_blank" rel="noreferrer">STX Apps Co., Ltd.</a> (each an &quot;App&quot; and collectively, the &quot;App(s)&quot;), or accessing, browsing and/or using any other mobile or web services owned, controlled or offered by STX Apps Co., Ltd. (the Site(s), the App(s) and any such other services (collectively, the &quot;Service&quot;)), you acknowledge that you have read and understood and agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, then please cease using the Service immediately and you must uninstall the App(s) from any device owned or controlled by you. STX Apps Co., Ltd. (&quot;STX Apps&quot;) reserves the right to change these Terms at any time. We recommend that you periodically check the Site(s) for changes. By accessing, browsing and/or using any Service after these updates to these Terms have been posted, you agree to be bound by the updated Terms. THESE TERMS CONSTITUTE A BINDING AGREEMENT BETWEEN YOU AND STX APPS. In addition, the STX Apps Privacy Policy governs your access to and use of the Service and the processing of certain information about you.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Rights to use the service</h2>
            <p className={tailwind('pt-3 leading-7')}>Subject to your compliance with these Terms in all material respects, STX Apps grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to (i) access and view pages from the Service for your personal, non-commercial use only; and (ii) print a reasonable number of such pages for your personal, non-commercial use only. Your access to and use of the Service must further comply in all material respects with any instructions and guidelines (&quot;Guidelines&quot;) posted on the Site(s) and/or communicated through the App(s).</p>
            <p className={tailwind('pt-5 leading-7')}>Subject to your compliance with these Terms in all material respects, STX Apps further grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to install and use the App(s), in machine executable object code form only, on a single compatible personal mobile device that you own and control, solely for personal, non-commercial purposes. Your license to any App(s) is also governed by the applicable terms of service, policies and procedures of the App Store through which you download the App(s) (the &quot;App Store Terms&quot;). These Terms amend and supplement the applicable App Store Terms and to the extent that these Terms contradict or are inconsistent with the applicable App Store Terms, the App Store Terms control and prevail. You are authorized to download the App(s) solely via the App Stores, if any, through which we make them available for download. You acknowledge that by downloading an App(s) via an App Store, you are subject to the applicable App Store Terms.</p>
            <p className={tailwind('pt-5 leading-7')}>STX Apps reserves the right to terminate or suspend your license to use all or any portion of the Service and your other rights under these Terms at any time and for any reason, including, but not limited to, violation of these Terms, the Guidelines and/or any applicable App Store Terms. Upon such termination, all license and other rights granted to you under these Terms will immediately terminate, but all other provisions of these Terms will survive termination. You will immediately cease all use of the Service and remove and destroy all copies of the App(s) from your mobile devices.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>No warranty and limitation of liability</h2>
            <p className={tailwind('pt-3 leading-7')}>STX APPS PROVIDES THE SITE(S), THE APP(S) AND THE OTHER SERVICE ON AN &quot;AS IS&quot;, &quot;WITH ALL FAULTS&quot; AND &quot;AS AVAILABLE&quot; BASIS. STX APPS AND ITS PARENTS, SUBSIDIARIES AND AFFILIATES, AND EACH OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS (THE &quot;STX APPS PARTIES&quot;) DISCLAIM ALL WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, OR ARISING FROM STATUTE, COURSE OF DEALING, USAGE OF TRADE OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, INTEGRATION, INTEROPERABILITY OR QUIET ENJOYMENT. THE STX APPS PARTIES MAKE NO REPRESENTATIONS OR WARRANTIES ABOUT THE ACCURACY OR COMPLETENESS, CURRENCY, OR NON-INFRINGEMENT OF THE SERVICE OR OF THE INFORMATION OR OTHER CONTENT CONTAINED IN OR ACCESSIBLE THROUGH THE SERVICE. THE STX APPS PARTIES DO NOT WARRANT THAT THE FUNCTIONS OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICE OR THE SERVERS THAT MAKE THE SERVICE AVAILABLE WILL BE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU.</p>
            <p className={tailwind('pt-5 leading-7')}>YOU UNDERSTAND AND AGREE THAT YOU USE THE SERVICE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGES THAT ARISE FROM SUCH USE. UNDER NO CIRCUMSTANCES SHALL THE STX APPS PARTIES BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES OF ANY KIND, OR ANY OTHER DAMAGES WHATSOEVER (HOWEVER ARISING, INCLUDING BY NEGLIGENCE), INCLUDING WITHOUT LIMITATION, DAMAGES RELATED TO USE, MISUSE, RELIANCE ON, INABILITY TO USE AND INTERRUPTION, SUSPENSION, OR TERMINATION OF ANY OF THE SERVICE AND DAMAGES RESULTING FROM LOSS OF USE OR DATA, WHETHER OR NOT THE STX APPS PARTIES HAVE BEEN ADVISED OF SUCH POSSIBILITY AND REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE. YOUR ONLY RIGHT WITH RESPECT TO ANY DISSATISFACTION WITH THE SERVICE SHALL BE TO TERMINATE YOUR USE OF THE SERVICE. IN NO EVENT SHALL THE STX APPS PARTIES&apos; TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING UNDER THESE TERMS OR YOUR USE OF THE SERVICE EXCEED THE TOTAL AMOUNT PAID BY YOU TO STX APPS FOR USE OF THE SERVICE DURING ANY ONE MONTH. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.</p>
            <p className={tailwind('pt-5 leading-7')}>YOU UNDERSTAND THAT YOUR USE OF THE SERVICE MAY INVOLVE KNOWN AND UNANTICIPATED RISKS THAT COULD RESULT IN INJURY OR ILLNESS, INCLUDING, BUT NOT LIMITED TO, DANGERS THAT MAY BE CAUSED BY THE ACTS OR INTENTIONS OF OTHER USERS OR OTHER THIRD PARTIES (INCLUDING WITHOUT LIMITATION, REGARDING ANY CONTENT (FOR EXAMPLE, INAPPROPRIATE OR EXPLICIT CONTENT) THAT YOU, ANOTHER USER OR A THIRD PARTY POSTS, STORES, SHARES, SENDS, TRANSMITS, DISSEMINATES, OR RECEIVES THROUGH THE SERVICE), OR OCCURRENCES BEYOND THE CONTROL OF THE STX APPS PARTIES. BY USING THE SERVICE, YOU ASSUME ALL SUCH RISKS AND DANGERS AND ALL RESPONSIBILITY FOR ANY LOSSES AND/OR DAMAGES. YOU VOLUNTARILY RELEASE, WAIVE, DISCHARGE AND HOLD HARMLESS THE STX APPS PARTIES FROM ANY AND ALL CLAIMS, DEMANDS OR CAUSES OF ACTION FOR BODILY INJURY, PROPERTY DAMAGE, WRONGFUL DEATH, LOSS OF SERVICE OR OTHER CLAIMS THAT IN ANY WAY ARISE FROM OR ARE RELATED TO YOUR USE OF THE SERVICE. THE SERVICE IS INTENDED ONLY AS PERSONAL, GEOGRAPHIC LOCATION-BASED SERVICE FOR INDIVIDUAL USE. YOU ACKNOWLEDGE AND AGREE THAT STX APPS HAS OFFERED THE SERVICE, SET ITS PRICES, AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE FOREGOING WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY. YOU FURTHER ACKNOWLEDGE AND AGREE THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH IN THESE TERMS REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN YOU AND STX APPS, AND THAT THE WARRANTY DISCLAIMERS AND THE LIMITATIONS OF LIABILITY SET FORTH IN THESE TERMS FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND STX APPS. STX APPS WOULD NOT BE ABLE TO PROVIDE THE SERVICE TO YOU ON AN ECONOMICALLY REASONABLE BASIS WITHOUT THESE LIMITATIONS AND DISCLAIMERS.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Links to external materials</h2>
            <p className={tailwind('pt-3 leading-7')}>The Service may provide links to other websites, mobile device software applications, services or resources. You acknowledge and agree that the STX Apps Parties do not endorse and are not responsible for any content, advertising, products, services or other materials on or available through such sites or resources (&quot;External Materials&quot;). External Materials are subject to different terms and conditions and privacy policies, which you are responsible for reviewing. You further acknowledge and agree that the STX Apps Parties shall not be liable for any damage or loss caused by or resulting from use of or reliance on any External Materials.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>System requirements</h2>
            <p className={tailwind('pt-3 leading-7')}>Use of the Service requires compatible hardware (fees may apply), Internet access (fees may apply), and certain software (fees may apply), and may require obtaining updates or upgrades from time to time. Because use of the Service involves hardware, software, and Internet access, your ability to use the Service may be affected by the performance of these factors. You acknowledge and agree that such system requirements, which may be changed from time to time, are your responsibility.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Changes to the Service</h2>
            <p className={tailwind('pt-3 leading-7')}>STX Apps reserves the right at any time to modify or discontinue, temporarily or permanently, the Service (or any portion thereof) with or without notice and without liability to you. You agree that the STX Apps Parties shall not be liable to you or any third party for any modification, suspension or discontinuance of the Service (or any portion thereof).</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Changes to these Terms</h2>
            <p className={tailwind('pt-3 leading-7')}>STX Apps may revise these Terms at any time without notice. By using the Service you are agreeing to be bound by the then current version of these Terms.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Our content</h2>
            <p className={tailwind('pt-3 leading-7')}>STX Apps or its licensors and suppliers own all rights, title and interest in the App(s) and the software and other technology used to provide the Service and all associated intellectual property rights (&quot;Our Technology&quot;), and Our Technology is protected by copyright and other intellectual property laws and treaties. Our Technology is licensed, not sold, to you for use only under the terms and conditions of these Terms. STX Apps reserves all rights not expressly granted to you.</p>
            <p className={tailwind('pt-5 leading-7')}>Brace.to, the Brace.to logo, Brace.to product screen shots and the Brace.to &quot;B&quot; App Icon design and Justnote, the Justnote logo, Justnote product screen shot and the Justnote &quot;N&quot; App Icon design are trademarks or the subject of other intellectual property rights of STX Apps, and may not be used without prior, express written permission from STX Apps. All other trademarks not owned by STX Apps that appear on the Service are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by STX Apps. All content included on the Service, including all information, data, text, software, music, sounds, photographs, graphics, videos, messages, scripts, tags, compilations of the foregoing and/or other materials accessible through the Service, including all associated intellectual property rights (&quot;Our Content&quot;), is the property of STX Apps and/or its licensors, as applicable, and protected by intellectual property and other laws and treaties. Except as expressly permitted under these Terms, no reproduction, transmission, modification or display of any of Our Content is permitted without our prior, express written permission.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Your account and Secret Key</h2>
            <p className={tailwind('pt-3 leading-7')}>Your account is a Stacks account, and a Stacks account is used to access the Stacks blockchain and a Stacks data server. The Stacks blockchain stores your account information, such as your username, profile, and data server location. A Stacks data server stores your encrypted app data.</p>
            <p className={tailwind('pt-5 leading-7')}>You are responsible for the security of your account, and you agree to accept responsibility for all activities that occur under your account whether or not authorized by you. The STX Apps Parties will not be liable for any loss or damage arising from unauthorized use of your Account.</p>
            <p className={tailwind('pt-5 leading-7')}>You acknowledge that you need your Secret Key to access your account and the Secret Key is provided only when you sign up. If you lose your Secret Key, your Secret Key will be lost forever. Only you know your Secret Key, which means that no one can help you recover it. You agree that the STX Apps Parties shall not be liable for any loss or damage arising from the unaccessible of your account.</p>
            <p className={tailwind('pt-5 leading-7')}>Your Secret Key cannot be changed or reset. As it&apos;s used to encrypt your content file by file, if you change your Secret Key, every file needs to be decrypted with your old Secret Key and encrypted again with your new Secret Key.</p>
            <p className={tailwind('pt-5 leading-7')}>You acknowledge that your Stacks account is generated by a cryptographic algorithm and your Secret Key. You agree that forgetting your Secret Key is the only way to delete your account.</p>
            <p className={tailwind('pt-5 leading-7')}>If you create an account with STX Apps, we create your Stacks account without a username, profile, or data server location. So no data is stored in the Stacks blockchain. You acknowledge that as no specified data server location, your data is stored in our provided server by default. You agree that if no data is stored in the Stacks blockchain, after deleting all your data in our data server, there is no data left.</p>
            <p className={tailwind('pt-5 leading-7')}>If you use your Stacks account to access and store any data on the Stacks blockchain, you acknowledge that the data cannot be deleted. You agree that the STX Apps Parties shall not be liable for any damage arising from the information exposed forever on the blockchain.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Information you provide and Your data</h2>
            <p className={tailwind('pt-3 leading-7')}>You agree to read our Privacy Policy, which explains what type of information we collect and what might happen to that information, including, without limitation, how such information is shared and used. Our Privacy Policy also explains how we retain and delete the collected information and how you can request deletion of your information.</p>
            <p className={tailwind('pt-5 leading-7')}>You agree that if you have not signed in or performed any activity for at least 2 years, we reserve the right to delete your data in our data server due to inactivity.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Fees and subscription</h2>
            <p className={tailwind('pt-3 leading-7')}>While the basic functionality of the Service is free for use, additional data charges may apply to you for mobile use of the Service through your mobile device. Additional fees may also apply for using additional features of the Service. If there is a charge associated with a portion of the Service, you agree to pay that charge for accessing or using it. The price stated for the Service may be denominated in your local currency by Apple App Store, Google Play Store, Paddle Checkout, or any other applicable App Store/payment processing service. Fees and charges are collected by the App Store or payment processing service. You should consult with them to determine if the price charged includes all applicable taxes and currency exchange settlements. STX Apps also relies on them to collect subscription fees and to report on the status of subscription accounts. Your access to the additional features may be suspended or canceled if you do not make your payment on time and/or in full.</p>
            <p className={tailwind('pt-5 leading-7')}>If you purchase one or more subscriptions or sign up for one or more trial subscriptions to the Service, then the following terms apply:</p>
            <ol className={tailwind('list-[lower-alpha]')}>
              <li className={tailwind('ml-10 pt-5')}>Auto-Renewal. YOU AGREE THAT, ONCE YOUR SUBSCRIPTION PERIOD EXPIRES, YOUR SUBSCRIPTION(S) WILL AUTOMATICALLY RENEW FOR SUCCESSIVE PERIODS EQUAL IN LENGTH TO THE IMMEDIATELY PRECEDING SUBSCRIPTION PERIOD UNLESS AND UNTIL YOU CANCEL YOUR SUBSCRIPTION(S). You acknowledge and agree that deletion of your account does not cancel your subscription(s) and you must cancel your subscription(s) explicitly through the applicable App Store or payment processing service.</li>
              <li className={tailwind('ml-10 pt-5')}>Recurring Charges. If you register for a paid subscription, YOU AUTHORIZE STX APPS&apos; APPLICABLE SERVICE PROVIDER TO PROCESS YOUR PAYMENTS FOR ANY RENEWAL SUBSCRIPTION(S). SUBSCRIPTION PRICES WILL BE PROVIDED TO YOU AT THE TIME OF PURCHASE. YOU WILL BE BILLED FOR THE SAME SUBSCRIPTION PLAN(S) (OR THE MOST SIMILAR SUBSCRIPTION PLAN(S), IF YOUR PRIOR PLAN(S) ARE NO LONGER AVAILABLE) AT THE THEN-CURRENT SUBSCRIPTION PRICE PLUS ANY APPLICABLE TAXES. YOUR PAYMENTS WILL BE PROCESSED FOR ANY RENEWAL SUBSCRIPTION(S) USING THE SAME BILLING CYCLE AS YOUR CURRENT SUBSCRIPTION(S). IN OTHER WORDS, ON WHICHEVER DAY YOUR PAYMENT IS PROCESSED FOR YOUR CURRENT SUBSCRIPTION(S), YOUR PAYMENT WILL CONTINUE TO BE PROCESSED ON THAT DAY FOR ANY RENEWAL SUBSCRIPTION(S). ADDITIONAL TERMS AND CONDITIONS MAY APPLY UPON RENEWAL, AND SUBSCRIPTION FEES MAY CHANGE AT ANY TIME, TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW. However, if you do not agree to an applicable change in fees, you may cancel your subscription(s) at any time in accordance below.</li>
              <li className={tailwind('ml-10 pt-5')}>Cancellation. YOU MAY CANCEL YOUR SUBSCRIPTION(S) AT ANY TIME THROUGH THE APPLE APP STORE (IF YOU MANAGE YOUR SUBSCRIPTION(S) THROUGH AN IOS-BASED DEVICE) OR THROUGH THE GOOGLE PLAY STORE (IF YOU MANAGE YOUR SUBSCRIPTION(S) THROUGH AN ANDROID DEVICE) OR THROUGH PADDLE CHECKOUT (IF YOU MANAGE YOUR SUBSCRIPTION(S) THROUGH WEB PLATFORM). STX APPS HAS NO OBLIGATION TO OFFER OR PROVIDE ANY REFUND FOR THE CANCELLATION OF ANY SUBSCRIPTION, BUT YOU CAN CONTINUE TO USE THE SUBSCRIPTION SERVICE UNTIL THE END OF THE SUBSCRIPTION PERIOD YOU PAID FOR.</li>
            </ol>
            <p className={tailwind('pt-5 leading-7')}>You must make all payments for a charge through the applicable App Store or payment processing service. You agree to pay all fees and charges incurred in connection with your use of the Service (including any applicable taxes) at the rates in effect when the charges were incurred. BETWEEN YOU AND STX APPS, YOU, AND NOT STX APPS, ARE RESPONSIBLE FOR PAYING ANY AMOUNTS FOR THE SERVICE BILLED TO YOUR MOBILE DEVICE, PAYPAL, CREDIT OR DEBIT CARD BY AN APP STORE, PAYMENT PROCESSING SERVICE, OR THIRD PARTY WHO HAD ACCESS TO THESE ACCOUNTS, WHETHER OR NOT SUCH AMOUNTS WERE AUTHORIZED BY YOU.</p>
            <p className={tailwind('pt-5 leading-7')}>We reserve the right in the future to charge for use of our services that are currently available free of charge. You will not be charged for using any service unless you have opted for a paid subscription plan.</p>
            <p className={tailwind('pt-5 leading-7')}>We may decide to stop offering subscriptions at any time, including in response to unforeseen circumstances beyond our control, or to comply with a legal requirement; if so, we&apos;ll cancel your subscription(s) and refund the prorated portion of any prepaid subscription fee(s) equal to the remaining unused term of the subscription.</p>
            <p className={tailwind('pt-5 leading-7')}>We do not issue refunds for paid subscriptions. You may do so with the App Store or payment processing service through which you purchase the subscription, subject to the applicable App Store or payment processing service terms, i.e., if you&apos;ve purchased a subscription on your iOS device, such as an iPhone, iPad, or iPod touch, you may request a refund via the Apple App Store (support.apple.com/en-us/HT204084).</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Indemnification</h2>
            <p className={tailwind('pt-3 leading-7')}>You agree to indemnify, defend, and hold the STX Apps Parties harmless from and against any and all claims, suits, actions, losses, costs, damages, and any other liabilities, including attorneys&apos; fees, arising out of or related to your use of the Service and/or your interactions with other users of the Service, including, but not limited to, (i) your use or misuse of any geographic location information or the Service generally, (ii) any violation of the rights of any other person or entity by you, (iii) any breach or violation by you of these Terms or any law, regulation or guidance, (iv) your access to and use of the Service, including without limitation, to communicate with or meet another user in-person or to locate and attend any offline place or event or to post, store, share, send, transmit, or disseminate any content, or (v) any negligent acts, omissions or willful misconduct by you. STX Apps reserves the right to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Dispute resolution</h2>
            <p className={tailwind('pt-3 leading-7')}>Any dispute arising out of or relating to these Terms, including the alleged breach, termination, validity, interpretation, and performance thereof (&quot;Dispute&quot;) shall be resolved with the following procedures:</p>
            <ol className={tailwind('list-[lower-alpha]')}>
              <li className={tailwind('ml-10 pt-5')}>Negotiation. Upon written notice of any Dispute, the parties shall attempt to resolve it promptly by negotiation.</li>
              <li className={tailwind('ml-10 pt-5')}>Mediation. If the dispute has not been resolved by negotiation, then the Parties shall proceed to mediation. The parties shall agree on a mediator. If they cannot agree, the Thailand Arbitration Center shall appoint one to commence the mediation process.</li>
              <li className={tailwind('ml-10 pt-5')}>Arbitration. Any Dispute not resolved through negotiation or mediation shall be resolved by final and binding arbitration in accordance with the rules of Thailand Arbitration Center Rule on Mediation, B.E. 2557 (2014). The arbitration will be held in Bangkok, Thailand using one or more neutral arbitrators as a panel.</li>
            </ol>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Governing law</h2>
            <p className={tailwind('pt-3 leading-7')}>These Terms and your relationship with STX Apps under these Terms shall be governed by and construed and enforced in accordance with the laws of the Kingdom of Thailand, without regard to principles of conflict of laws. The court of competent jurisdiction in Thailand will have exclusive jurisdiction in case of any dispute of any kind that might arise between you and us.</p>

            <h2 className={tailwind('pt-8 text-xl font-semibold text-gray-900')}>Miscellaneous</h2>
            <p className={tailwind('pt-3 leading-7')}>If any provision of these Terms is held to be invalid or unenforceable under applicable law, then such provision shall be construed, limited, modified or, if necessary, severed to the extent necessary to eliminate its invalidity or unenforceability, without in any way affecting the remaining parts of these Terms. Such provision shall be ineffective to the extent of such invalidity or unenforceability only, without in any way affecting the remaining parts of these Terms.</p>
            <p className={tailwind('pt-5 leading-7')}>A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of any party at any time to require performance of any provision of these Terms shall in no manner affect such party&apos;s right at a later time to enforce the same. A waiver of any breach of any provision of these Terms shall not be construed as a continuing waiver of other breaches of the same or other provisions of these Terms.</p>
            <p className={tailwind('pt-5 leading-7')}>These Terms shall be binding upon and inure to the benefit of the parties hereto and their respective successors and permitted assigns. You may not assign any of your rights or obligations under these Terms to another party without the express written consent of STX Apps.</p>
            <p className={tailwind('pt-5 leading-7')}>The parties acknowledge that these Terms are concluded between you and STX Apps only, and not with the owner or operator of any other applicable App Store through which you may have downloaded the App(s) (the &quot;App Store Owner&quot;), and the App Store Owner is not responsible for the App(s) and the contents thereof. The App Store Owner has no obligation whatsoever to furnish any maintenance and support services with respect to the App(s). STX Apps, not the App Store Owner, is responsible for addressing any claims from you or any third party relating to the App(s) or your possession and/or use of the App(s), including, but not limited to, product liability claims, any claim that the App(s)s fails to conform to any applicable legal or regulatory requirement and claims arising under consumer protection or similar legislation. The App Store Owner and its subsidiaries are third party beneficiaries of these Terms, and shall have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary hereof.</p>
            <p className={tailwind('pt-5 leading-7')}>These Terms constitute the complete and exclusive statement of the agreement between STX Apps and you with respect to the subject matter hereof and supersede any proposal or prior or contemporaneous agreement, oral or written, and any other communications between the parties in relation to the subject matter of these Terms.</p>
            <p className={tailwind('pt-5 leading-7')}>You represent and warrant that you are not (i) located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &quot;terrorist supporting&quot; country; and (ii) listed on any U.S. Government list of prohibited or restricted parties, including, but not limited to, the Specially Designated Nationals List.</p>
            <p className={tailwind('pt-5 leading-7')}>YOU AND STX APPS AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICE MUST COMMENCE WITHIN ONE YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION SHALL BE PERMANENTLY BARRED.</p>

            <p className={tailwind('pt-5 leading-7')}>If you have questions or concerns regarding these Terms or your subscription(s), you can contact us at <a className={tailwind('rounded-xs font-medium text-gray-900 underline focus:outline-none focus:ring')} href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#115;&#117;&#112;&#112;&#111;&#114;&#116;&#64;&#98;&#114;&#97;&#99;&#101;&#46;&#116;&#111;"><span className={tailwind('e-mail')} data-user="troppus" data-website="ot.ecarb"></span></a>. Alternatively, you may contact us at:</p>
            <p className={tailwind('pt-3 leading-7')}>STX Apps Co., Ltd.<br />ATTN: Brace.to Team<br />247 Chan 31 Sathon<br />Bangkok 10120 TH</p>

            <div className={tailwind('pt-12 text-right')}>
              <button className={tailwind('group rounded-xs hover:text-gray-600 focus:outline-none focus:ring')} onClick={() => window.scrollTo(0, 0)}>
                <span className={tailwind('pl-1')}>Back to top</span>
                <svg className={tailwind('mb-1 ml-1 inline-block w-5 text-gray-400 group-hover:text-gray-500')} viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fillRule="evenodd" clipRule="evenodd" d="M3.29289 9.70711C2.90237 9.31658 2.90237 8.68342 3.29289 8.29289L9.29289 2.29289C9.68342 1.90237 10.3166 1.90237 10.7071 2.29289L16.7071 8.29289C17.0976 8.68342 17.0976 9.31658 16.7071 9.70711C16.3166 10.0976 15.6834 10.0976 15.2929 9.70711L11 5.41421V17C11 17.5523 10.5523 18 10 18C9.44772 18 9 17.5523 9 17V5.41421L4.70711 9.70711C4.31658 10.0976 3.68342 10.0976 3.29289 9.70711Z" />
                </svg>
              </button>
              <br />
              <Link className={tailwind('group mt-2 inline-block rounded-xs hover:text-gray-600 focus:outline-none focus:ring')} href="/">
                <span className={tailwind('pl-0.5')}>Go home</span>
                <svg className={tailwind('mb-1 ml-1 inline-block w-5 text-gray-400 group-hover:text-gray-500')} viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M10.7071 2.29289C10.3166 1.90237 9.68342 1.90237 9.29289 2.29289L2.29289 9.29289C1.90237 9.68342 1.90237 10.3166 2.29289 10.7071C2.68342 11.0976 3.31658 11.0976 3.70711 10.7071L4 10.4142V17C4 17.5523 4.44772 18 5 18H7C7.55228 18 8 17.5523 8 17V15C8 14.4477 8.44772 14 9 14H11C11.5523 14 12 14.4477 12 15V17C12 17.5523 12.4477 18 13 18H15C15.5523 18 16 17.5523 16 17V10.4142L16.2929 10.7071C16.6834 11.0976 17.3166 11.0976 17.7071 10.7071C18.0976 10.3166 18.0976 9.68342 17.7071 9.29289L10.7071 2.29289Z" />
                </svg>
              </Link>
            </div>
          </div>
        </div>
        <Footer />
      </React.Fragment>
    );
  }
}

const mapStateToProps = (state, props) => {
  return {
    themeMode: getThemeMode(state),
    safeAreaWidth: getSafeAreaWidth(state),
  };
};

export default connect(mapStateToProps)(withTailwind(Terms));
