export const INIT = 'INIT';

export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const UPDATE_HISTORY_POSITION = 'UPDATE_HISTORY_POSITION';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_POPUP = 'UPDATE_POPUP';

export const FETCH_LINKS = 'FETCH_LINKS';
export const FETCH_LINKS_COMMIT = 'FETCH_LINKS_COMMIT';
export const FETCH_LINKS_ROLLBACK = 'FETCH_LINKS_ROLLBACK';

export const ADD_LINK = 'ADD_LINK';
export const ADD_LINK_COMMIT = 'ADD_LINK_COMMIT';
export const ADD_LINK_ROLLBACK = 'ADD_LINK_ROLLBACK';

export const MOVE_LINKS_ADD_STEP = 'MOVE_LINKS_ADD_STEP';
export const MOVE_LINKS_ADD_STEP_COMMIT = 'MOVE_LINKS_ADD_STEP_COMMIT';
export const MOVE_LINKS_ADD_STEP_ROLLBACK = 'MOVE_LINKS_ADD_STEP_ROLLBACK';
export const MOVE_LINKS_DELETE_STEP = 'MOVE_LINKS_DELETE_STEP';
export const MOVE_LINKS_DELETE_STEP_COMMIT = 'MOVE_LINKS_DELETE_STEP_COMMIT';
export const MOVE_LINKS_DELETE_STEP_ROLLBACK = 'MOVE_LINKS_DELETE_STEP_ROLLBACK';

export const DELETE_LINKS = 'DELETE_LINKS';
export const DELETE_LINKS_COMMIT = 'DELETE_LINKS_COMMIT';
export const DELETE_LINKS_ROLLBACK = 'DELETE_LINKS_ROLLBACK';

export const DISPLAY_MORE_LINKS = 'DISPLAY_MORE_LINKS';
