export const INIT = 'INIT';

export const UPDATE_WINDOW = 'UPDATE_WINDOW';
export const UPDATE_HISTORY_POSITION = 'UPDATE_HISTORY_POSITION';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';

export const FETCH = 'FETCH';
export const FETCH_COMMIT = 'FETCH_COMMIT';
export const FETCH_ROLLBACK = 'FETCH_ROLLBACK';

export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_MORE_COMMIT = 'FETCH_MORE_COMMIT';
export const FETCH_MORE_ROLLBACK = 'FETCH_MORE_ROLLBACK';

export const ADD_LINKS = 'ADD_LINKS';
export const ADD_LINKS_COMMIT = 'ADD_LINKS_COMMIT';
export const ADD_LINKS_ROLLBACK = 'ADD_LINKS_ROLLBACK';

export const UPDATE_LINKS = 'UPDATE_LINKS';

export const DELETE_LINKS = 'DELETE_LINKS';
export const DELETE_LINKS_COMMIT = 'DELETE_LINKS_COMMIT';
export const DELETE_LINKS_ROLLBACK = 'DELETE_LINKS_ROLLBACK';

export const MOVE_LINKS_ADD_STEP = 'MOVE_LINKS_ADD_STEP';
export const MOVE_LINKS_ADD_STEP_COMMIT = 'MOVE_LINKS_ADD_STEP_COMMIT';
export const MOVE_LINKS_ADD_STEP_ROLLBACK = 'MOVE_LINKS_ADD_STEP_ROLLBACK';
export const MOVE_LINKS_DELETE_STEP = 'MOVE_LINKS_DELETE_STEP';
export const MOVE_LINKS_DELETE_STEP_COMMIT = 'MOVE_LINKS_DELETE_STEP_COMMIT';
export const MOVE_LINKS_DELETE_STEP_ROLLBACK = 'MOVE_LINKS_DELETE_STEP_ROLLBACK';

export const CANCEL_DIED_LINKS = 'CANCEL_DIED_LINKS';

export const DELETE_OLD_LINKS_IN_TRASH = 'DELETE_OLD_LINKS_IN_TRASH';
export const DELETE_OLD_LINKS_IN_TRASH_COMMIT = 'DELETE_OLD_LINKS_IN_TRASH_COMMIT';
export const DELETE_OLD_LINKS_IN_TRASH_ROLLBACK = 'DELETE_OLD_LINKS_IN_TRASH_ROLLBACK';

export const EXTRACT_CONTENTS = 'EXTRACT_CONTENTS';
export const EXTRACT_CONTENTS_COMMIT = 'EXTRACT_CONTENTS_COMMIT';
export const EXTRACT_CONTENTS_ROLLBACK = 'EXTRACT_CONTENTS_ROLLBACK';

export const UPDATE_STATUS = 'UPDATE_STATUS';

export const UPDATE_CARD_ITEM_MENU_POPUP_POSITION = 'UPDATE_CARD_ITEM_MENU_POPUP_POSITION';

export const RESET_STATE = 'RESET_STATE';
